### ISSUE TITLE
關於Roadmap?

### ISSUE THREAD

**Issue by 409544041** [michael811125/OxGFrame#1]
您好，感覺這個框架蠻好用的，很適合獨立游戲和商業手游。有roadmap的計劃麽，打算長期使用這個框架。謝謝。

**Comment by michael811125** [comment]
不會意思這麼晚回覆, 是有的只是還沒有列舉, 基本上後續會開始著手計畫擴展支援程式熱更新 （可能會採用新的 HybirdCLR 或是 toLua）, 也會針對一系列的 Debug 進行系列擴展（透過統一封裝接口實現 Log 檔案寫入等）, 後續有完整的設計計畫也會更新在 README 中, 如果使用上有任何問題或者可以優化的地方隨時提出來, 非常感謝你。

**Comment by 409544041** [comment]
感謝你的回覆。非常滿意。
