### ISSUE TITLE
How to generate HotfixPackage for HybridCLR WebGL?

### ISSUE THREAD

**Issue by westernholdur** [michael811125/OxGFrame#37]
![image](https://github.com/user-attachments/assets/8dfd1949-8613-4b30-a97c-3424917c9769)

**Comment by 1ookilo** [comment]
![1121](https://github.com/user-attachments/assets/68d0a31d-ddb0-47c3-bb00-bb77b39c1507)

**Comment by 1ookilo** [comment]
![5112314](https://github.com/user-attachments/assets/cfacdc28-028e-4b94-b45f-21a7aeec99e6)
