### ISSUE TITLE
添加一个日志模块，可以开关各个块的日志

### ISSUE THREAD

**Issue by yingnierxiao** [michael811125/OxGFrame#5]
![image](https://github.com/michael811125/OxGFrame/assets/3435706/54b5375a-5a58-4ec6-81e1-20421e7e9349)
这样方便关闭不需要的模块的日志

**Comment by michael811125** [comment]
可以, 下个版本我再全部更改可以开关日志的相关配置

**Comment by michael811125** [comment]
新版本 [![version](https://img.shields.io/badge/version-2.7.7-yellow.svg)](https://github.com/michael811125/OxGFrame/releases/tag/v2.7.7) 已经有安装日志系统了，并且也将框架升级 YooAsset 至 v1.5.4-preview (作者有合并你的 PR 了)。

**Comment by yingnierxiao** [comment]
> 新版本 [![version](https://camo.githubusercontent.com/60f88013ee1e936f819fca89a79f8145e6c2bd79f890de6da55fa77daadcad81/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f76657273696f6e2d322e372e372d79656c6c6f772e737667)](https://github.com/michael811125/OxGFrame/releases/tag/v2.7.7) 已经有安装日志系统了，并且也将框架升级 YooAsset 至 v1.5.4-preview (作者有合并你的 PR 了)。
如果日志能保存为文件更方便在设备上面调试，比如log4net等库，不过大家好像都不喜欢引入新的库。

**Comment by michael811125** [comment]
> 如果日志能保存为文件更方便在设备上面调试，比如log4net等库，不过大家好像都不喜欢引入新的库。

原本想说保存为文件自己建立 Logger 实现，因为有提供了 Logging 接口可以 override，只是框架中的 Logger 没有实现保存功能，那后续有需要我再导入。
