### ISSUE TITLE
如果加载资源不存在就会无限循环，直到编辑器奔溃

### ISSUE THREAD

**Issue by yingnierxiao** [michael811125/OxGFrame#6]
OxGFrame.AssetLoader.Cacher.CacheBundle:LoadAsset<UnityEngine.Texture2DArray> (string,string,OxGFrame.AssetLoader.Progression) (at ./Library/PackageCache/com.michaelo.oxgframe@2388b052cf/AssetLoader/Scripts/Runtime/Cacher/CacheBundle.cs:957)
希望有机制超过一定时间不存在就直接返回错误

**Comment by michael811125** [comment]
> OxGFrame.AssetLoader.Cacher.CacheBundle:LoadAsset<UnityEngine.Texture2DArray> (string,string,OxGFrame.AssetLoader.Progression) (at ./Library/PackageCache/com.michaelo.oxgframe@2388b052cf/AssetLoader/Scripts/Runtime/Cacher/CacheBundle.cs:957)
> 
> 希望有机制超过一定时间不存在就直接返回错误 

好的，那我在加入 retry count。

**Comment by michael811125** [comment]
已在 [v2.7.8](https://github.com/michael811125/OxGFrame/releases/tag/v2.7.8) 加入 retry counter 机制了，也可在加载调用 API 时，带入最大尝试次数 (预设 = 3)。

**Comment by michael811125** [comment]
后续检测一下发现 retry counter 有一些判定上的瑕疵，与包括错误卸载类型问题，已有在 [v2.7.9](https://github.com/michael811125/OxGFrame/releases/tag/v2.7.9) 修正了。

**Comment by yingnierxiao** [comment]
YooAsset.YooAssets.CheckLocationValid
可以用这个接口判断资源是否存在，不过在大量实例化的时候，有些资源即使存在AssetLoaders.InstantiateAssetAsync返回的也是null，这个我暂时没去找原因

**Comment by michael811125** [comment]
好的，我会排查一下。
