### ISSUE TITLE
大量加载预制件的时候会提示部分预制件加载不到的情况，用YooAssets接口就不会出现问题

### ISSUE THREAD

**Issue by yingnierxiao** [michael811125/OxGFrame#7]
// var mapobj = await AssetLoaders.InstantiateAssetAsync<GameObject>(obj.UnitConfigName);

 var handle = YooAssets.LoadAssetAsync<GameObject>(obj.UnitConfigName);

**Comment by michael811125** [comment]
你实际大量实例化是多少数量？我在来检测一下。

**Comment by michael811125** [comment]
如果加载类型错误会返回 null (RawFile 跟 Asset 区别)。

**Comment by michael811125** [comment]
我这边会在 AssetObject 那层在增加判定，不过如果有确切原因在帮我回报一下，谢了。

**Comment by yingnierxiao** [comment]
大概500来个 加载都都是prefab,部分加载成功

**Comment by michael811125** [comment]
好的，那我再看一下是不是哪边出了问题。

**Comment by michael811125** [comment]
我重新调整判断后，测试 AssetLoaders.InstantiateAssetAsync 加载并实例 600 个不同的预制件 AB 包 (真机)，全都有加载成功，不过我会再检查一下，确定没什么判定上的问题就会更新版本。

![image](https://github.com/michael811125/OxGFrame/assets/30960759/27cc94d1-3a05-47c6-aab2-396f46db8fff)

**Comment by michael811125** [comment]
![image](https://github.com/michael811125/OxGFrame/assets/30960759/63b3e4d4-5963-43a7-b053-f25c01a435d0)

**Comment by michael811125** [comment]
已有优化 [v2.7.10](https://github.com/michael811125/OxGFrame/releases/tag/v2.7.10)。

**Comment by yingnierxiao** [comment]
现在正常了

**Comment by michael811125** [comment]
好的
