### ISSUE TITLE
How to set / change "yoo" download folder?

### ISSUE THREAD

**Issue by reidsneo** [michael811125/OxGFrame#8]
Hello, thanks for the amazing library!
I don't have enough knowledge in C# and Unity, but based on my trial error I managed to get the OxGFrame working on my project.
I cannot change default "yoo" folder, I see it referenced in GetLocalSandboxRootPath() but I cannot set it.
I want to change this "yoo" folder to something different.

Thanks!

**Comment by michael811125** [comment]
Hi, you can search to find YooAssetSettings to edit it in project.

![image](https://github.com/michael811125/OxGFrame/assets/30960759/8d6c1331-4e42-4d3b-be0e-beb0f713de12)

**Comment by reidsneo** [comment]
Hi, thank you for the answer!
issue can be closed now
