### ISSUE TITLE
SimpleDiskUtils The name 'GetDrive' does not exist in the current context 

### ISSUE THREAD

**Issue by reidsneo** [michael811125/OxGFrame#9]
Hi I tried to install the latest Kit to fresh project (I follow step from the readme in repo)
but somehow missing script on "PatchLauncher" prefab
SimpleDiskUtils also complains which not able to get "GetDrive" method

![image](https://github.com/michael811125/OxGFrame/assets/12298979/9f31dea7-d362-4699-95b7-9371d3d65412)

Thanks!

**Comment by michael811125** [comment]
delete and reload BundleDemo try again!

**Comment by reidsneo** [comment]
I double check by reinstall the OxGFrame and also remove the sample still not working.
my machine is Linux Ubuntu 22.04 with vulkan driver, I see that DiskUtils doesn't support "WebGL" also "Linux" right?, X86_64 only support WinAPI
how can I still using the Kit regardless the DiskUtils?

`Library/PackageCache/com.michaelo.oxgframe@5f46802502/AssetLoader/ThirdParty/SimpleDiskUtils/Runtime/DiskUtils.cs(144,25): error CS0103: The name 'GetDrive' does not exist in the current context
`

`Library/PackageCache/com.michaelo.oxgframe@5f46802502/AssetLoader/ThirdParty/SimpleDiskUtils/Runtime/DiskUtils.cs(155,25): error CS0103: The name 'GetDrive' does not exist in the current context`

`Library/PackageCache/com.michaelo.oxgframe@5f46802502/AssetLoader/ThirdParty/SimpleDiskUtils/Runtime/DiskUtils.cs(166,25): error CS0103: The name 'GetDrive' does not exist in the current context
`

Thanks!

**Comment by michael811125** [comment]
Yes, DiskUtils does not support Linux. You need to use windows os, or you can use 2.9.12 if you have some reason need to use Linux to dev (but recommend use newest).

**Comment by reidsneo** [comment]
Hi michael,
tried the solution in link above it _working good for now_, doesn't complain any error anymore
later in the PatchLauncher Prefabs, I can uncheck the Diskutils whenever I not used this, so I can still use the latest version of the OxGFrame kit
let me try few more time, and keep this issue open for a moment, I will get back with the result (to check any of side effect occured)

**Comment by michael811125** [comment]
ok, i will replace it in next version, thank you a lot.
